name: dartx
description: Parser and utilities for DartX.
version: 0.0.9
repository: https://github.com/ykmnkmi/dartx.dart

environment:
  sdk: ^3.5.0

dependencies:
  _fe_analyzer_shared: ^67.0.0
  analyzer: ^6.4.1
  dart_style: ^2.3.6
  source_span: ^1.10.0

dev_dependencies:
  build_runner: ^2.4.12
  build_web_compilers: ^4.0.11
  lints: ^4.0.0
  stack_trace: ^1.11.1
  web: ^1.0.0
