name: dartx
description: Parser and utilities for DartX.
version: 0.0.4
repository: https://github.com/ykmnkmi/dartx.dart

environment:
  sdk: ^3.4.0

dependencies:
  _fe_analyzer_shared: ^67.0.0
  analyzer: ^6.4.1
  dart_style: ^2.3.6
  source_span: ^1.10.0

dev_dependencies:
  lints: ^4.0.0
  stack_trace: ^1.11.1
